// DO NOT EDIT. This file was autogenerated by parse.assembly

// Package bt7 defines chromosome and assembly fragment intervals for the bt7 genome assembly for cow.
package bt7

import (
	"github.com/biogo/biogo/feat/genome"
)

var (
	Chr1  = genome.Chromosome{Chr: "Chr1", Desc: "Chromosome", Length: 161428367}
	Chr2  = genome.Chromosome{Chr: "Chr2", Desc: "Chromosome", Length: 141965563}
	Chr3  = genome.Chromosome{Chr: "Chr3", Desc: "Chromosome", Length: 126844711}
	Chr4  = genome.Chromosome{Chr: "Chr4", Desc: "Chromosome", Length: 123809850}
	Chr5  = genome.Chromosome{Chr: "Chr5", Desc: "Chromosome", Length: 125249322}
	Chr6  = genome.Chromosome{Chr: "Chr6", Desc: "Chromosome", Length: 122519025}
	Chr7  = genome.Chromosome{Chr: "Chr7", Desc: "Chromosome", Length: 113029157}
	Chr8  = genome.Chromosome{Chr: "Chr8", Desc: "Chromosome", Length: 116846264}
	Chr9  = genome.Chromosome{Chr: "Chr9", Desc: "Chromosome", Length: 108503706}
	Chr10 = genome.Chromosome{Chr: "Chr10", Desc: "Chromosome", Length: 105982576}
	Chr11 = genome.Chromosome{Chr: "Chr11", Desc: "Chromosome", Length: 109987751}
	Chr12 = genome.Chromosome{Chr: "Chr12", Desc: "Chromosome", Length: 85119472}
	Chr13 = genome.Chromosome{Chr: "Chr13", Desc: "Chromosome", Length: 84213851}
	Chr14 = genome.Chromosome{Chr: "Chr14", Desc: "Chromosome", Length: 81216349}
	Chr15 = genome.Chromosome{Chr: "Chr15", Desc: "Chromosome", Length: 84472747}
	Chr16 = genome.Chromosome{Chr: "Chr16", Desc: "Chromosome", Length: 77710258}
	Chr17 = genome.Chromosome{Chr: "Chr17", Desc: "Chromosome", Length: 76280064}
	Chr18 = genome.Chromosome{Chr: "Chr18", Desc: "Chromosome", Length: 65811054}
	Chr19 = genome.Chromosome{Chr: "Chr19", Desc: "Chromosome", Length: 64845320}
	Chr20 = genome.Chromosome{Chr: "Chr20", Desc: "Chromosome", Length: 75686341}
	Chr21 = genome.Chromosome{Chr: "Chr21", Desc: "Chromosome", Length: 69078422}
	Chr22 = genome.Chromosome{Chr: "Chr22", Desc: "Chromosome", Length: 61598339}
	Chr23 = genome.Chromosome{Chr: "Chr23", Desc: "Chromosome", Length: 52334015}
	Chr24 = genome.Chromosome{Chr: "Chr24", Desc: "Chromosome", Length: 64508398}
	Chr25 = genome.Chromosome{Chr: "Chr25", Desc: "Chromosome", Length: 44081797}
	Chr26 = genome.Chromosome{Chr: "Chr26", Desc: "Chromosome", Length: 51826547}
	Chr27 = genome.Chromosome{Chr: "Chr27", Desc: "Chromosome", Length: 48460478}
	Chr28 = genome.Chromosome{Chr: "Chr28", Desc: "Chromosome", Length: 45964680}
	Chr29 = genome.Chromosome{Chr: "Chr29", Desc: "Chromosome", Length: 51812796}
	ChrX  = genome.Chromosome{Chr: "ChrX", Desc: "Chromosome", Length: 88654062}
	ChrY  = genome.Chromosome{Chr: "ChrY", Desc: "Chromosome", Length: 43300181}
	ChrM  = genome.Chromosome{Chr: "ChrM", Desc: "Chromosome", Length: 16338}
)

var Chromosomes = []*genome.Chromosome{
	&Chr1,
	&Chr2,
	&Chr3,
	&Chr4,
	&Chr5,
	&Chr6,
	&Chr7,
	&Chr8,
	&Chr9,
	&Chr10,
	&Chr11,
	&Chr12,
	&Chr13,
	&Chr14,
	&Chr15,
	&Chr16,
	&Chr17,
	&Chr18,
	&Chr19,
	&Chr20,
	&Chr21,
	&Chr22,
	&Chr23,
	&Chr24,
	&Chr25,
	&Chr26,
	&Chr27,
	&Chr28,
	&Chr29,
	&ChrX,
	&ChrY,
	&ChrM,
}
