// DO NOT EDIT. This file was autogenerated by parse.karyotype

// Package mouse defines chromosome and band intervals for the mouse karyotype.
package mouse

import (
	"code.google.com/p/biogo/feat"
	"code.google.com/p/biogo/feat/genome"
)

var (
	Chr1  = genome.Chromosome{Chr: "Chr1", Desc: "Chromosome", Length: 195471971}
	Chr2  = genome.Chromosome{Chr: "Chr2", Desc: "Chromosome", Length: 182113224}
	Chr3  = genome.Chromosome{Chr: "Chr3", Desc: "Chromosome", Length: 160039680}
	Chr4  = genome.Chromosome{Chr: "Chr4", Desc: "Chromosome", Length: 156508116}
	Chr5  = genome.Chromosome{Chr: "Chr5", Desc: "Chromosome", Length: 151834684}
	Chr6  = genome.Chromosome{Chr: "Chr6", Desc: "Chromosome", Length: 149736546}
	Chr7  = genome.Chromosome{Chr: "Chr7", Desc: "Chromosome", Length: 145441459}
	Chr8  = genome.Chromosome{Chr: "Chr8", Desc: "Chromosome", Length: 129401213}
	Chr9  = genome.Chromosome{Chr: "Chr9", Desc: "Chromosome", Length: 124595110}
	Chr10 = genome.Chromosome{Chr: "Chr10", Desc: "Chromosome", Length: 130694993}
	Chr11 = genome.Chromosome{Chr: "Chr11", Desc: "Chromosome", Length: 122082543}
	Chr12 = genome.Chromosome{Chr: "Chr12", Desc: "Chromosome", Length: 120129022}
	Chr13 = genome.Chromosome{Chr: "Chr13", Desc: "Chromosome", Length: 120421639}
	Chr14 = genome.Chromosome{Chr: "Chr14", Desc: "Chromosome", Length: 124902244}
	Chr15 = genome.Chromosome{Chr: "Chr15", Desc: "Chromosome", Length: 104043685}
	Chr16 = genome.Chromosome{Chr: "Chr16", Desc: "Chromosome", Length: 98207768}
	Chr17 = genome.Chromosome{Chr: "Chr17", Desc: "Chromosome", Length: 94987271}
	Chr18 = genome.Chromosome{Chr: "Chr18", Desc: "Chromosome", Length: 90702639}
	Chr19 = genome.Chromosome{Chr: "Chr19", Desc: "Chromosome", Length: 61431566}
	ChrX  = genome.Chromosome{Chr: "ChrX", Desc: "Chromosome", Length: 171031299}
	ChrY  = genome.Chromosome{Chr: "ChrY", Desc: "Chromosome", Length: 91744698}
)

var Chromosomes = []*genome.Chromosome{
	&Chr1,
	&Chr2,
	&Chr3,
	&Chr4,
	&Chr5,
	&Chr6,
	&Chr7,
	&Chr8,
	&Chr9,
	&Chr10,
	&Chr11,
	&Chr12,
	&Chr13,
	&Chr14,
	&Chr15,
	&Chr16,
	&Chr17,
	&Chr18,
	&Chr19,
	&ChrX,
	&ChrY,
}

var (
	Chr1_qA1    = genome.Band{Band: "qA1", Desc: "Band", StartPos: 0, EndPos: 8840440, Giemsa: "gpos100", Chr: &Chr1}
	Chr1_qA2    = genome.Band{Band: "qA2", Desc: "Band", StartPos: 8840440, EndPos: 12278390, Giemsa: "gneg", Chr: &Chr1}
	Chr1_qA3    = genome.Band{Band: "qA3", Desc: "Band", StartPos: 12278390, EndPos: 20136559, Giemsa: "gpos33", Chr: &Chr1}
	Chr1_qA4    = genome.Band{Band: "qA4", Desc: "Band", StartPos: 20136559, EndPos: 22101102, Giemsa: "gneg", Chr: &Chr1}
	Chr1_qA5    = genome.Band{Band: "qA5", Desc: "Band", StartPos: 22101102, EndPos: 30941543, Giemsa: "gpos100", Chr: &Chr1}
	Chr1_qB     = genome.Band{Band: "qB", Desc: "Band", StartPos: 30941543, EndPos: 43219933, Giemsa: "gneg", Chr: &Chr1}
	Chr1_qC1_1  = genome.Band{Band: "qC1.1", Desc: "Band", StartPos: 43219933, EndPos: 54516052, Giemsa: "gpos66", Chr: &Chr1}
	Chr1_qC1_2  = genome.Band{Band: "qC1.2", Desc: "Band", StartPos: 54516052, EndPos: 55989459, Giemsa: "gneg", Chr: &Chr1}
	Chr1_qC1_3  = genome.Band{Band: "qC1.3", Desc: "Band", StartPos: 55989459, EndPos: 59427408, Giemsa: "gpos75", Chr: &Chr1}
	Chr1_qC2    = genome.Band{Band: "qC2", Desc: "Band", StartPos: 59427408, EndPos: 65321035, Giemsa: "gneg", Chr: &Chr1}
	Chr1_qC3    = genome.Band{Band: "qC3", Desc: "Band", StartPos: 65321035, EndPos: 74652612, Giemsa: "gpos33", Chr: &Chr1}
	Chr1_qC4    = genome.Band{Band: "qC4", Desc: "Band", StartPos: 74652612, EndPos: 80055103, Giemsa: "gneg", Chr: &Chr1}
	Chr1_qC5    = genome.Band{Band: "qC5", Desc: "Band", StartPos: 80055103, EndPos: 87422137, Giemsa: "gpos33", Chr: &Chr1}
	Chr1_qD     = genome.Band{Band: "qD", Desc: "Band", StartPos: 87422137, EndPos: 99700527, Giemsa: "gneg", Chr: &Chr1}
	Chr1_qE1_1  = genome.Band{Band: "qE1.1", Desc: "Band", StartPos: 99700527, EndPos: 102647341, Giemsa: "gpos33", Chr: &Chr1}
	Chr1_qE1_2  = genome.Band{Band: "qE1.2", Desc: "Band", StartPos: 102647341, EndPos: 103629612, Giemsa: "gneg", Chr: &Chr1}
	Chr1_qE2_1  = genome.Band{Band: "qE2.1", Desc: "Band", StartPos: 103629612, EndPos: 112470053, Giemsa: "gpos100", Chr: &Chr1}
	Chr1_qE2_2  = genome.Band{Band: "qE2.2", Desc: "Band", StartPos: 112470053, EndPos: 113943460, Giemsa: "gneg", Chr: &Chr1}
	Chr1_qE2_3  = genome.Band{Band: "qE2.3", Desc: "Band", StartPos: 113943460, EndPos: 125730715, Giemsa: "gpos100", Chr: &Chr1}
	Chr1_qE3    = genome.Band{Band: "qE3", Desc: "Band", StartPos: 125730715, EndPos: 128677528, Giemsa: "gneg", Chr: &Chr1}
	Chr1_qE4    = genome.Band{Band: "qE4", Desc: "Band", StartPos: 128677528, EndPos: 139482511, Giemsa: "gpos66", Chr: &Chr1}
	Chr1_qF     = genome.Band{Band: "qF", Desc: "Band", StartPos: 139482511, EndPos: 147340681, Giemsa: "gneg", Chr: &Chr1}
	Chr1_qG1    = genome.Band{Band: "qG1", Desc: "Band", StartPos: 147340681, EndPos: 151760902, Giemsa: "gpos100", Chr: &Chr1}
	Chr1_qG2    = genome.Band{Band: "qG2", Desc: "Band", StartPos: 151760902, EndPos: 152743173, Giemsa: "gneg", Chr: &Chr1}
	Chr1_qG3    = genome.Band{Band: "qG3", Desc: "Band", StartPos: 152743173, EndPos: 157163393, Giemsa: "gpos100", Chr: &Chr1}
	Chr1_qH1    = genome.Band{Band: "qH1", Desc: "Band", StartPos: 157163393, EndPos: 160110207, Giemsa: "gneg", Chr: &Chr1}
	Chr1_qH2_1  = genome.Band{Band: "qH2.1", Desc: "Band", StartPos: 160110207, EndPos: 164039292, Giemsa: "gpos33", Chr: &Chr1}
	Chr1_qH2_2  = genome.Band{Band: "qH2.2", Desc: "Band", StartPos: 164039292, EndPos: 165512699, Giemsa: "gneg", Chr: &Chr1}
	Chr1_qH2_3  = genome.Band{Band: "qH2.3", Desc: "Band", StartPos: 165512699, EndPos: 169932919, Giemsa: "gpos33", Chr: &Chr1}
	Chr1_qH3    = genome.Band{Band: "qH3", Desc: "Band", StartPos: 169932919, EndPos: 175826546, Giemsa: "gneg", Chr: &Chr1}
	Chr1_qH4    = genome.Band{Band: "qH4", Desc: "Band", StartPos: 175826546, EndPos: 181720174, Giemsa: "gpos33", Chr: &Chr1}
	Chr1_qH5    = genome.Band{Band: "qH5", Desc: "Band", StartPos: 181720174, EndPos: 188104936, Giemsa: "gneg", Chr: &Chr1}
	Chr1_qH6    = genome.Band{Band: "qH6", Desc: "Band", StartPos: 188104936, EndPos: 195471971, Giemsa: "gpos33", Chr: &Chr1}
	Chr2_qA1    = genome.Band{Band: "qA1", Desc: "Band", StartPos: 0, EndPos: 14080919, Giemsa: "gpos100", Chr: &Chr2}
	Chr2_qA2    = genome.Band{Band: "qA2", Desc: "Band", StartPos: 14080919, EndPos: 16427739, Giemsa: "gneg", Chr: &Chr2}
	Chr2_qA3    = genome.Band{Band: "qA3", Desc: "Band", StartPos: 16427739, EndPos: 29100566, Giemsa: "gpos33", Chr: &Chr2}
	Chr2_qB     = genome.Band{Band: "qB", Desc: "Band", StartPos: 29100566, EndPos: 48344489, Giemsa: "gneg", Chr: &Chr2}
	Chr2_qC1_1  = genome.Band{Band: "qC1.1", Desc: "Band", StartPos: 48344489, EndPos: 60547953, Giemsa: "gpos100", Chr: &Chr2}
	Chr2_qC1_2  = genome.Band{Band: "qC1.2", Desc: "Band", StartPos: 60547953, EndPos: 61017317, Giemsa: "gneg", Chr: &Chr2}
	Chr2_qC1_3  = genome.Band{Band: "qC1.3", Desc: "Band", StartPos: 61017317, EndPos: 68527140, Giemsa: "gpos100", Chr: &Chr2}
	Chr2_qC2    = genome.Band{Band: "qC2", Desc: "Band", StartPos: 68527140, EndPos: 71812688, Giemsa: "gneg", Chr: &Chr2}
	Chr2_qC3    = genome.Band{Band: "qC3", Desc: "Band", StartPos: 71812688, EndPos: 81199968, Giemsa: "gpos66", Chr: &Chr2}
	Chr2_qD     = genome.Band{Band: "qD", Desc: "Band", StartPos: 81199968, EndPos: 88709792, Giemsa: "gneg", Chr: &Chr2}
	Chr2_qE1    = genome.Band{Band: "qE1", Desc: "Band", StartPos: 88709792, EndPos: 101382619, Giemsa: "gpos100", Chr: &Chr2}
	Chr2_qE2    = genome.Band{Band: "qE2", Desc: "Band", StartPos: 101382619, EndPos: 105137531, Giemsa: "gneg", Chr: &Chr2}
	Chr2_qE3    = genome.Band{Band: "qE3", Desc: "Band", StartPos: 105137531, EndPos: 113116719, Giemsa: "gpos33", Chr: &Chr2}
	Chr2_qE4    = genome.Band{Band: "qE4", Desc: "Band", StartPos: 113116719, EndPos: 115932902, Giemsa: "gneg", Chr: &Chr2}
	Chr2_qE5    = genome.Band{Band: "qE5", Desc: "Band", StartPos: 115932902, EndPos: 123912090, Giemsa: "gpos66", Chr: &Chr2}
	Chr2_qF1    = genome.Band{Band: "qF1", Desc: "Band", StartPos: 123912090, EndPos: 131891278, Giemsa: "gneg", Chr: &Chr2}
	Chr2_qF2    = genome.Band{Band: "qF2", Desc: "Band", StartPos: 131891278, EndPos: 134707462, Giemsa: "gpos33", Chr: &Chr2}
	Chr2_qF3    = genome.Band{Band: "qF3", Desc: "Band", StartPos: 134707462, EndPos: 141278557, Giemsa: "gneg", Chr: &Chr2}
	Chr2_qG1    = genome.Band{Band: "qG1", Desc: "Band", StartPos: 141278557, EndPos: 146910925, Giemsa: "gpos100", Chr: &Chr2}
	Chr2_qG2    = genome.Band{Band: "qG2", Desc: "Band", StartPos: 146910925, EndPos: 147849653, Giemsa: "gneg", Chr: &Chr2}
	Chr2_qG3    = genome.Band{Band: "qG3", Desc: "Band", StartPos: 147849653, EndPos: 152543293, Giemsa: "gpos100", Chr: &Chr2}
	Chr2_qH1    = genome.Band{Band: "qH1", Desc: "Band", StartPos: 152543293, EndPos: 159114389, Giemsa: "gneg", Chr: &Chr2}
	Chr2_qH2    = genome.Band{Band: "qH2", Desc: "Band", StartPos: 159114389, EndPos: 163338664, Giemsa: "gpos33", Chr: &Chr2}
	Chr2_qH3    = genome.Band{Band: "qH3", Desc: "Band", StartPos: 163338664, EndPos: 173664672, Giemsa: "gneg", Chr: &Chr2}
	Chr2_qH4    = genome.Band{Band: "qH4", Desc: "Band", StartPos: 173664672, EndPos: 182113224, Giemsa: "gpos33", Chr: &Chr2}
	Chr3_qA1    = genome.Band{Band: "qA1", Desc: "Band", StartPos: 0, EndPos: 18541182, Giemsa: "gpos100", Chr: &Chr3}
	Chr3_qA2    = genome.Band{Band: "qA2", Desc: "Band", StartPos: 18541182, EndPos: 20492885, Giemsa: "gneg", Chr: &Chr3}
	Chr3_qA3    = genome.Band{Band: "qA3", Desc: "Band", StartPos: 20492885, EndPos: 35618587, Giemsa: "gpos66", Chr: &Chr3}
	Chr3_qB     = genome.Band{Band: "qB", Desc: "Band", StartPos: 35618587, EndPos: 46840881, Giemsa: "gneg", Chr: &Chr3}
	Chr3_qC     = genome.Band{Band: "qC", Desc: "Band", StartPos: 46840881, EndPos: 56599399, Giemsa: "gpos100", Chr: &Chr3}
	Chr3_qD     = genome.Band{Band: "qD", Desc: "Band", StartPos: 56599399, EndPos: 60990731, Giemsa: "gneg", Chr: &Chr3}
	Chr3_qE1    = genome.Band{Band: "qE1", Desc: "Band", StartPos: 60990731, EndPos: 69773397, Giemsa: "gpos33", Chr: &Chr3}
	Chr3_qE2    = genome.Band{Band: "qE2", Desc: "Band", StartPos: 69773397, EndPos: 72700952, Giemsa: "gneg", Chr: &Chr3}
	Chr3_qE3    = genome.Band{Band: "qE3", Desc: "Band", StartPos: 72700952, EndPos: 83923246, Giemsa: "gpos100", Chr: &Chr3}
	Chr3_qF1    = genome.Band{Band: "qF1", Desc: "Band", StartPos: 83923246, EndPos: 93193838, Giemsa: "gneg", Chr: &Chr3}
	Chr3_qF2_1  = genome.Band{Band: "qF2.1", Desc: "Band", StartPos: 93193838, EndPos: 97585170, Giemsa: "gpos33", Chr: &Chr3}
	Chr3_qF2_2  = genome.Band{Band: "qF2.2", Desc: "Band", StartPos: 97585170, EndPos: 106367836, Giemsa: "gneg", Chr: &Chr3}
	Chr3_qF2_3  = genome.Band{Band: "qF2.3", Desc: "Band", StartPos: 106367836, EndPos: 108319539, Giemsa: "gpos33", Chr: &Chr3}
	Chr3_qF3    = genome.Band{Band: "qF3", Desc: "Band", StartPos: 108319539, EndPos: 115150501, Giemsa: "gneg", Chr: &Chr3}
	Chr3_qG1    = genome.Band{Band: "qG1", Desc: "Band", StartPos: 115150501, EndPos: 126860721, Giemsa: "gpos100", Chr: &Chr3}
	Chr3_qG2    = genome.Band{Band: "qG2", Desc: "Band", StartPos: 126860721, EndPos: 128812425, Giemsa: "gneg", Chr: &Chr3}
	Chr3_qG3    = genome.Band{Band: "qG3", Desc: "Band", StartPos: 128812425, EndPos: 138570942, Giemsa: "gpos66", Chr: &Chr3}
	Chr3_qH1    = genome.Band{Band: "qH1", Desc: "Band", StartPos: 138570942, EndPos: 143938126, Giemsa: "gneg", Chr: &Chr3}
	Chr3_qH2    = genome.Band{Band: "qH2", Desc: "Band", StartPos: 143938126, EndPos: 148329459, Giemsa: "gpos33", Chr: &Chr3}
	Chr3_qH3    = genome.Band{Band: "qH3", Desc: "Band", StartPos: 148329459, EndPos: 154184569, Giemsa: "gneg", Chr: &Chr3}
	Chr3_qH4    = genome.Band{Band: "qH4", Desc: "Band", StartPos: 154184569, EndPos: 160039680, Giemsa: "gpos33", Chr: &Chr3}
	Chr4_qA1    = genome.Band{Band: "qA1", Desc: "Band", StartPos: 0, EndPos: 14882673, Giemsa: "gpos100", Chr: &Chr4}
	Chr4_qA2    = genome.Band{Band: "qA2", Desc: "Band", StartPos: 14882673, EndPos: 17763191, Giemsa: "gneg", Chr: &Chr4}
	Chr4_qA3    = genome.Band{Band: "qA3", Desc: "Band", StartPos: 17763191, EndPos: 28325088, Giemsa: "gpos100", Chr: &Chr4}
	Chr4_qA4    = genome.Band{Band: "qA4", Desc: "Band", StartPos: 28325088, EndPos: 30245433, Giemsa: "gneg", Chr: &Chr4}
	Chr4_qA5    = genome.Band{Band: "qA5", Desc: "Band", StartPos: 30245433, EndPos: 43687848, Giemsa: "gpos66", Chr: &Chr4}
	Chr4_qB1    = genome.Band{Band: "qB1", Desc: "Band", StartPos: 43687848, EndPos: 51849314, Giemsa: "gneg", Chr: &Chr4}
	Chr4_qB2    = genome.Band{Band: "qB2", Desc: "Band", StartPos: 51849314, EndPos: 55209918, Giemsa: "gpos33", Chr: &Chr4}
	Chr4_qB3    = genome.Band{Band: "qB3", Desc: "Band", StartPos: 55209918, EndPos: 63371384, Giemsa: "gneg", Chr: &Chr4}
	Chr4_qC1    = genome.Band{Band: "qC1", Desc: "Band", StartPos: 63371384, EndPos: 69612505, Giemsa: "gpos33", Chr: &Chr4}
	Chr4_qC2    = genome.Band{Band: "qC2", Desc: "Band", StartPos: 69612505, EndPos: 72012936, Giemsa: "gneg", Chr: &Chr4}
	Chr4_qC3    = genome.Band{Band: "qC3", Desc: "Band", StartPos: 72012936, EndPos: 84015092, Giemsa: "gpos100", Chr: &Chr4}
	Chr4_qC4    = genome.Band{Band: "qC4", Desc: "Band", StartPos: 84015092, EndPos: 89776127, Giemsa: "gneg", Chr: &Chr4}
	Chr4_qC5    = genome.Band{Band: "qC5", Desc: "Band", StartPos: 89776127, EndPos: 97457507, Giemsa: "gpos66", Chr: &Chr4}
	Chr4_qC6    = genome.Band{Band: "qC6", Desc: "Band", StartPos: 97457507, EndPos: 105618973, Giemsa: "gneg", Chr: &Chr4}
	Chr4_qC7    = genome.Band{Band: "qC7", Desc: "Band", StartPos: 105618973, EndPos: 110899922, Giemsa: "gpos66", Chr: &Chr4}
	Chr4_qD1    = genome.Band{Band: "qD1", Desc: "Band", StartPos: 110899922, EndPos: 117621130, Giemsa: "gneg", Chr: &Chr4}
	Chr4_qD2_1  = genome.Band{Band: "qD2.1", Desc: "Band", StartPos: 117621130, EndPos: 120501647, Giemsa: "gpos33", Chr: &Chr4}
	Chr4_qD2_2  = genome.Band{Band: "qD2.2", Desc: "Band", StartPos: 120501647, EndPos: 131063544, Giemsa: "gneg", Chr: &Chr4}
	Chr4_qD2_3  = genome.Band{Band: "qD2.3", Desc: "Band", StartPos: 131063544, EndPos: 133944062, Giemsa: "gpos33", Chr: &Chr4}
	Chr4_qD3    = genome.Band{Band: "qD3", Desc: "Band", StartPos: 133944062, EndPos: 141625442, Giemsa: "gneg", Chr: &Chr4}
	Chr4_qE1    = genome.Band{Band: "qE1", Desc: "Band", StartPos: 141625442, EndPos: 147866563, Giemsa: "gpos100", Chr: &Chr4}
	Chr4_qE2    = genome.Band{Band: "qE2", Desc: "Band", StartPos: 147866563, EndPos: 156508116, Giemsa: "gneg", Chr: &Chr4}
	Chr5_qA1    = genome.Band{Band: "qA1", Desc: "Band", StartPos: 0, EndPos: 14895174, Giemsa: "gpos100", Chr: &Chr5}
	Chr5_qA2    = genome.Band{Band: "qA2", Desc: "Band", StartPos: 14895174, EndPos: 16336643, Giemsa: "gneg", Chr: &Chr5}
	Chr5_qA3    = genome.Band{Band: "qA3", Desc: "Band", StartPos: 16336643, EndPos: 25465943, Giemsa: "gpos66", Chr: &Chr5}
	Chr5_qB1    = genome.Band{Band: "qB1", Desc: "Band", StartPos: 25465943, EndPos: 33634265, Giemsa: "gneg", Chr: &Chr5}
	Chr5_qB2    = genome.Band{Band: "qB2", Desc: "Band", StartPos: 33634265, EndPos: 35556223, Giemsa: "gpos33", Chr: &Chr5}
	Chr5_qB3    = genome.Band{Band: "qB3", Desc: "Band", StartPos: 35556223, EndPos: 50451398, Giemsa: "gneg", Chr: &Chr5}
	Chr5_qC1    = genome.Band{Band: "qC1", Desc: "Band", StartPos: 50451398, EndPos: 58619719, Giemsa: "gpos33", Chr: &Chr5}
	Chr5_qC2    = genome.Band{Band: "qC2", Desc: "Band", StartPos: 58619719, EndPos: 61022167, Giemsa: "gneg", Chr: &Chr5}
	Chr5_qC3_1  = genome.Band{Band: "qC3.1", Desc: "Band", StartPos: 61022167, EndPos: 71592936, Giemsa: "gpos100", Chr: &Chr5}
	Chr5_qC3_2  = genome.Band{Band: "qC3.2", Desc: "Band", StartPos: 71592936, EndPos: 73514894, Giemsa: "gneg", Chr: &Chr5}
	Chr5_qC3_3  = genome.Band{Band: "qC3.3", Desc: "Band", StartPos: 73514894, EndPos: 77839300, Giemsa: "gpos66", Chr: &Chr5}
	Chr5_qD     = genome.Band{Band: "qD", Desc: "Band", StartPos: 77839300, EndPos: 81683216, Giemsa: "gneg", Chr: &Chr5}
	Chr5_qE1    = genome.Band{Band: "qE1", Desc: "Band", StartPos: 81683216, EndPos: 91293006, Giemsa: "gpos100", Chr: &Chr5}
	Chr5_qE2    = genome.Band{Band: "qE2", Desc: "Band", StartPos: 91293006, EndPos: 93695453, Giemsa: "gneg", Chr: &Chr5}
	Chr5_qE3    = genome.Band{Band: "qE3", Desc: "Band", StartPos: 93695453, EndPos: 99461327, Giemsa: "gpos33", Chr: &Chr5}
	Chr5_qE4    = genome.Band{Band: "qE4", Desc: "Band", StartPos: 99461327, EndPos: 101863775, Giemsa: "gneg", Chr: &Chr5}
	Chr5_qE5    = genome.Band{Band: "qE5", Desc: "Band", StartPos: 101863775, EndPos: 107629649, Giemsa: "gpos33", Chr: &Chr5}
	Chr5_qF     = genome.Band{Band: "qF", Desc: "Band", StartPos: 107629649, EndPos: 124927271, Giemsa: "gneg", Chr: &Chr5}
	Chr5_qG1_1  = genome.Band{Band: "qG1.1", Desc: "Band", StartPos: 124927271, EndPos: 126849229, Giemsa: "gpos33", Chr: &Chr5}
	Chr5_qG1_2  = genome.Band{Band: "qG1.2", Desc: "Band", StartPos: 126849229, EndPos: 127810208, Giemsa: "gneg", Chr: &Chr5}
	Chr5_qG1_3  = genome.Band{Band: "qG1.3", Desc: "Band", StartPos: 127810208, EndPos: 130693145, Giemsa: "gpos33", Chr: &Chr5}
	Chr5_qG2    = genome.Band{Band: "qG2", Desc: "Band", StartPos: 130693145, EndPos: 146068809, Giemsa: "gneg", Chr: &Chr5}
	Chr5_qG3    = genome.Band{Band: "qG3", Desc: "Band", StartPos: 146068809, EndPos: 151834684, Giemsa: "gpos33", Chr: &Chr5}
	Chr6_qA1    = genome.Band{Band: "qA1", Desc: "Band", StartPos: 0, EndPos: 16637394, Giemsa: "gpos100", Chr: &Chr6}
	Chr6_qA2    = genome.Band{Band: "qA2", Desc: "Band", StartPos: 16637394, EndPos: 21530745, Giemsa: "gneg", Chr: &Chr6}
	Chr6_qA3_1  = genome.Band{Band: "qA3.1", Desc: "Band", StartPos: 21530745, EndPos: 27402766, Giemsa: "gpos100", Chr: &Chr6}
	Chr6_qA3_2  = genome.Band{Band: "qA3.2", Desc: "Band", StartPos: 27402766, EndPos: 28381436, Giemsa: "gneg", Chr: &Chr6}
	Chr6_qA3_3  = genome.Band{Band: "qA3.3", Desc: "Band", StartPos: 28381436, EndPos: 34253458, Giemsa: "gpos100", Chr: &Chr6}
	Chr6_qB1    = genome.Band{Band: "qB1", Desc: "Band", StartPos: 34253458, EndPos: 41593485, Giemsa: "gneg", Chr: &Chr6}
	Chr6_qB2_1  = genome.Band{Band: "qB2.1", Desc: "Band", StartPos: 41593485, EndPos: 44529495, Giemsa: "gpos66", Chr: &Chr6}
	Chr6_qB2_2  = genome.Band{Band: "qB2.2", Desc: "Band", StartPos: 44529495, EndPos: 45997501, Giemsa: "gneg", Chr: &Chr6}
	Chr6_qB2_3  = genome.Band{Band: "qB2.3", Desc: "Band", StartPos: 45997501, EndPos: 50890852, Giemsa: "gpos66", Chr: &Chr6}
	Chr6_qB3    = genome.Band{Band: "qB3", Desc: "Band", StartPos: 50890852, EndPos: 62634895, Giemsa: "gneg", Chr: &Chr6}
	Chr6_qC1    = genome.Band{Band: "qC1", Desc: "Band", StartPos: 62634895, EndPos: 74378937, Giemsa: "gpos100", Chr: &Chr6}
	Chr6_qC2    = genome.Band{Band: "qC2", Desc: "Band", StartPos: 74378937, EndPos: 76825613, Giemsa: "gneg", Chr: &Chr6}
	Chr6_qC3    = genome.Band{Band: "qC3", Desc: "Band", StartPos: 76825613, EndPos: 86122980, Giemsa: "gpos66", Chr: &Chr6}
	Chr6_qD1    = genome.Band{Band: "qD1", Desc: "Band", StartPos: 86122980, EndPos: 94441677, Giemsa: "gneg", Chr: &Chr6}
	Chr6_qD2    = genome.Band{Band: "qD2", Desc: "Band", StartPos: 94441677, EndPos: 95909683, Giemsa: "gpos33", Chr: &Chr6}
	Chr6_qD3    = genome.Band{Band: "qD3", Desc: "Band", StartPos: 95909683, EndPos: 103249709, Giemsa: "gneg", Chr: &Chr6}
	Chr6_qE1    = genome.Band{Band: "qE1", Desc: "Band", StartPos: 103249709, EndPos: 108632396, Giemsa: "gpos100", Chr: &Chr6}
	Chr6_qE2    = genome.Band{Band: "qE2", Desc: "Band", StartPos: 108632396, EndPos: 109611066, Giemsa: "gneg", Chr: &Chr6}
	Chr6_qE3    = genome.Band{Band: "qE3", Desc: "Band", StartPos: 109611066, EndPos: 116951093, Giemsa: "gpos100", Chr: &Chr6}
	Chr6_qF1    = genome.Band{Band: "qF1", Desc: "Band", StartPos: 116951093, EndPos: 122823114, Giemsa: "gneg", Chr: &Chr6}
	Chr6_qF2    = genome.Band{Band: "qF2", Desc: "Band", StartPos: 122823114, EndPos: 125269790, Giemsa: "gpos33", Chr: &Chr6}
	Chr6_qF3    = genome.Band{Band: "qF3", Desc: "Band", StartPos: 125269790, EndPos: 132120481, Giemsa: "gneg", Chr: &Chr6}
	Chr6_qG1    = genome.Band{Band: "qG1", Desc: "Band", StartPos: 132120481, EndPos: 139460508, Giemsa: "gpos66", Chr: &Chr6}
	Chr6_qG2    = genome.Band{Band: "qG2", Desc: "Band", StartPos: 139460508, EndPos: 142885854, Giemsa: "gneg", Chr: &Chr6}
	Chr6_qG3    = genome.Band{Band: "qG3", Desc: "Band", StartPos: 142885854, EndPos: 149736546, Giemsa: "gpos33", Chr: &Chr6}
	Chr7_qA1    = genome.Band{Band: "qA1", Desc: "Band", StartPos: 0, EndPos: 15202939, Giemsa: "gpos100", Chr: &Chr7}
	Chr7_qA2    = genome.Band{Band: "qA2", Desc: "Band", StartPos: 15202939, EndPos: 18243527, Giemsa: "gneg", Chr: &Chr7}
	Chr7_qA3    = genome.Band{Band: "qA3", Desc: "Band", StartPos: 18243527, EndPos: 28378821, Giemsa: "gpos33", Chr: &Chr7}
	Chr7_qB1    = genome.Band{Band: "qB1", Desc: "Band", StartPos: 28378821, EndPos: 34459997, Giemsa: "gneg", Chr: &Chr7}
	Chr7_qB2    = genome.Band{Band: "qB2", Desc: "Band", StartPos: 34459997, EndPos: 37500585, Giemsa: "gpos33", Chr: &Chr7}
	Chr7_qB3    = genome.Band{Band: "qB3", Desc: "Band", StartPos: 37500585, EndPos: 47635878, Giemsa: "gneg", Chr: &Chr7}
	Chr7_qB4    = genome.Band{Band: "qB4", Desc: "Band", StartPos: 47635878, EndPos: 54223819, Giemsa: "gpos33", Chr: &Chr7}
	Chr7_qB5    = genome.Band{Band: "qB5", Desc: "Band", StartPos: 54223819, EndPos: 60811759, Giemsa: "gneg", Chr: &Chr7}
	Chr7_qC     = genome.Band{Band: "qC", Desc: "Band", StartPos: 60811759, EndPos: 71453817, Giemsa: "gpos100", Chr: &Chr7}
	Chr7_qD1    = genome.Band{Band: "qD1", Desc: "Band", StartPos: 71453817, EndPos: 77028229, Giemsa: "gneg", Chr: &Chr7}
	Chr7_qD2    = genome.Band{Band: "qD2", Desc: "Band", StartPos: 77028229, EndPos: 80575581, Giemsa: "gpos66", Chr: &Chr7}
	Chr7_qD3    = genome.Band{Band: "qD3", Desc: "Band", StartPos: 80575581, EndPos: 90204110, Giemsa: "gneg", Chr: &Chr7}
	Chr7_qE1    = genome.Band{Band: "qE1", Desc: "Band", StartPos: 90204110, EndPos: 99832639, Giemsa: "gpos100", Chr: &Chr7}
	Chr7_qE2    = genome.Band{Band: "qE2", Desc: "Band", StartPos: 99832639, EndPos: 102366462, Giemsa: "gneg", Chr: &Chr7}
	Chr7_qE3    = genome.Band{Band: "qE3", Desc: "Band", StartPos: 102366462, EndPos: 111488226, Giemsa: "gpos33", Chr: &Chr7}
	Chr7_qF1    = genome.Band{Band: "qF1", Desc: "Band", StartPos: 111488226, EndPos: 118582931, Giemsa: "gneg", Chr: &Chr7}
	Chr7_qF2    = genome.Band{Band: "qF2", Desc: "Band", StartPos: 118582931, EndPos: 123143813, Giemsa: "gpos33", Chr: &Chr7}
	Chr7_qF3    = genome.Band{Band: "qF3", Desc: "Band", StartPos: 123143813, EndPos: 137333224, Giemsa: "gneg", Chr: &Chr7}
	Chr7_qF4    = genome.Band{Band: "qF4", Desc: "Band", StartPos: 137333224, EndPos: 140880577, Giemsa: "gpos33", Chr: &Chr7}
	Chr7_qF5    = genome.Band{Band: "qF5", Desc: "Band", StartPos: 140880577, EndPos: 145441459, Giemsa: "gneg", Chr: &Chr7}
	Chr8_qA1_1  = genome.Band{Band: "qA1.1", Desc: "Band", StartPos: 0, EndPos: 15940729, Giemsa: "gpos100", Chr: &Chr8}
	Chr8_qA1_2  = genome.Band{Band: "qA1.2", Desc: "Band", StartPos: 15940729, EndPos: 16878419, Giemsa: "gneg", Chr: &Chr8}
	Chr8_qA1_3  = genome.Band{Band: "qA1.3", Desc: "Band", StartPos: 16878419, EndPos: 20160333, Giemsa: "gpos33", Chr: &Chr8}
	Chr8_qA2    = genome.Band{Band: "qA2", Desc: "Band", StartPos: 20160333, EndPos: 29537233, Giemsa: "gneg", Chr: &Chr8}
	Chr8_qA3    = genome.Band{Band: "qA3", Desc: "Band", StartPos: 29537233, EndPos: 33756838, Giemsa: "gpos33", Chr: &Chr8}
	Chr8_qA4    = genome.Band{Band: "qA4", Desc: "Band", StartPos: 33756838, EndPos: 44071427, Giemsa: "gneg", Chr: &Chr8}
	Chr8_qB1_1  = genome.Band{Band: "qB1.1", Desc: "Band", StartPos: 44071427, EndPos: 48291032, Giemsa: "gpos66", Chr: &Chr8}
	Chr8_qB1_2  = genome.Band{Band: "qB1.2", Desc: "Band", StartPos: 48291032, EndPos: 50166412, Giemsa: "gneg", Chr: &Chr8}
	Chr8_qB1_3  = genome.Band{Band: "qB1.3", Desc: "Band", StartPos: 50166412, EndPos: 55792551, Giemsa: "gpos66", Chr: &Chr8}
	Chr8_qB2    = genome.Band{Band: "qB2", Desc: "Band", StartPos: 55792551, EndPos: 59543311, Giemsa: "gneg", Chr: &Chr8}
	Chr8_qB3_1  = genome.Band{Band: "qB3.1", Desc: "Band", StartPos: 59543311, EndPos: 67044831, Giemsa: "gpos100", Chr: &Chr8}
	Chr8_qB3_2  = genome.Band{Band: "qB3.2", Desc: "Band", StartPos: 67044831, EndPos: 67982521, Giemsa: "gneg", Chr: &Chr8}
	Chr8_qB3_3  = genome.Band{Band: "qB3.3", Desc: "Band", StartPos: 67982521, EndPos: 74546350, Giemsa: "gpos100", Chr: &Chr8}
	Chr8_qC1    = genome.Band{Band: "qC1", Desc: "Band", StartPos: 74546350, EndPos: 80172490, Giemsa: "gneg", Chr: &Chr8}
	Chr8_qC2    = genome.Band{Band: "qC2", Desc: "Band", StartPos: 80172490, EndPos: 84860940, Giemsa: "gpos33", Chr: &Chr8}
	Chr8_qC3    = genome.Band{Band: "qC3", Desc: "Band", StartPos: 84860940, EndPos: 90018235, Giemsa: "gneg", Chr: &Chr8}
	Chr8_qC4    = genome.Band{Band: "qC4", Desc: "Band", StartPos: 90018235, EndPos: 91424770, Giemsa: "gpos33", Chr: &Chr8}
	Chr8_qC5    = genome.Band{Band: "qC5", Desc: "Band", StartPos: 91424770, EndPos: 95644374, Giemsa: "gneg", Chr: &Chr8}
	Chr8_qD1    = genome.Band{Band: "qD1", Desc: "Band", StartPos: 95644374, EndPos: 103145894, Giemsa: "gpos100", Chr: &Chr8}
	Chr8_qD2    = genome.Band{Band: "qD2", Desc: "Band", StartPos: 103145894, EndPos: 104083584, Giemsa: "gneg", Chr: &Chr8}
	Chr8_qD3    = genome.Band{Band: "qD3", Desc: "Band", StartPos: 104083584, EndPos: 110647414, Giemsa: "gpos33", Chr: &Chr8}
	Chr8_qE1    = genome.Band{Band: "qE1", Desc: "Band", StartPos: 110647414, EndPos: 123775073, Giemsa: "gneg", Chr: &Chr8}
	Chr8_qE2    = genome.Band{Band: "qE2", Desc: "Band", StartPos: 123775073, EndPos: 129401213, Giemsa: "gpos33", Chr: &Chr8}
	Chr9_qA1    = genome.Band{Band: "qA1", Desc: "Band", StartPos: 0, EndPos: 14412120, Giemsa: "gpos100", Chr: &Chr9}
	Chr9_qA2    = genome.Band{Band: "qA2", Desc: "Band", StartPos: 14412120, EndPos: 19526099, Giemsa: "gneg", Chr: &Chr9}
	Chr9_qA3    = genome.Band{Band: "qA3", Desc: "Band", StartPos: 19526099, EndPos: 24175170, Giemsa: "gpos33", Chr: &Chr9}
	Chr9_qA4    = genome.Band{Band: "qA4", Desc: "Band", StartPos: 24175170, EndPos: 38122384, Giemsa: "gneg", Chr: &Chr9}
	Chr9_qA5_1  = genome.Band{Band: "qA5.1", Desc: "Band", StartPos: 38122384, EndPos: 44166177, Giemsa: "gpos66", Chr: &Chr9}
	Chr9_qA5_2  = genome.Band{Band: "qA5.2", Desc: "Band", StartPos: 44166177, EndPos: 46490712, Giemsa: "gneg", Chr: &Chr9}
	Chr9_qA5_3  = genome.Band{Band: "qA5.3", Desc: "Band", StartPos: 46490712, EndPos: 54859040, Giemsa: "gpos66", Chr: &Chr9}
	Chr9_qB     = genome.Band{Band: "qB", Desc: "Band", StartPos: 54859040, EndPos: 63227369, Giemsa: "gneg", Chr: &Chr9}
	Chr9_qC     = genome.Band{Band: "qC", Desc: "Band", StartPos: 63227369, EndPos: 69736069, Giemsa: "gpos33", Chr: &Chr9}
	Chr9_qD     = genome.Band{Band: "qD", Desc: "Band", StartPos: 69736069, EndPos: 77639490, Giemsa: "gneg", Chr: &Chr9}
	Chr9_qE1    = genome.Band{Band: "qE1", Desc: "Band", StartPos: 77639490, EndPos: 82753468, Giemsa: "gpos33", Chr: &Chr9}
	Chr9_qE2    = genome.Band{Band: "qE2", Desc: "Band", StartPos: 82753468, EndPos: 84613097, Giemsa: "gneg", Chr: &Chr9}
	Chr9_qE3_1  = genome.Band{Band: "qE3.1", Desc: "Band", StartPos: 84613097, EndPos: 91121796, Giemsa: "gpos100", Chr: &Chr9}
	Chr9_qE3_2  = genome.Band{Band: "qE3.2", Desc: "Band", StartPos: 91121796, EndPos: 91586703, Giemsa: "gneg", Chr: &Chr9}
	Chr9_qE3_3  = genome.Band{Band: "qE3.3", Desc: "Band", StartPos: 91586703, EndPos: 100884846, Giemsa: "gpos100", Chr: &Chr9}
	Chr9_qE4    = genome.Band{Band: "qE4", Desc: "Band", StartPos: 100884846, EndPos: 101814660, Giemsa: "gpos66", Chr: &Chr9}
	Chr9_qF1    = genome.Band{Band: "qF1", Desc: "Band", StartPos: 101814660, EndPos: 108323360, Giemsa: "gneg", Chr: &Chr9}
	Chr9_qF2    = genome.Band{Band: "qF2", Desc: "Band", StartPos: 108323360, EndPos: 111112803, Giemsa: "gpos33", Chr: &Chr9}
	Chr9_qF3    = genome.Band{Band: "qF3", Desc: "Band", StartPos: 111112803, EndPos: 119946038, Giemsa: "gneg", Chr: &Chr9}
	Chr9_qF4    = genome.Band{Band: "qF4", Desc: "Band", StartPos: 119946038, EndPos: 124595110, Giemsa: "gpos33", Chr: &Chr9}
	Chr10_qA1   = genome.Band{Band: "qA1", Desc: "Band", StartPos: 0, EndPos: 12822904, Giemsa: "gpos100", Chr: &Chr10}
	Chr10_qA2   = genome.Band{Band: "qA2", Desc: "Band", StartPos: 12822904, EndPos: 17754791, Giemsa: "gneg", Chr: &Chr10}
	Chr10_qA3   = genome.Band{Band: "qA3", Desc: "Band", StartPos: 17754791, EndPos: 23673055, Giemsa: "gpos33", Chr: &Chr10}
	Chr10_qA4   = genome.Band{Band: "qA4", Desc: "Band", StartPos: 23673055, EndPos: 33536828, Giemsa: "gneg", Chr: &Chr10}
	Chr10_qB1   = genome.Band{Band: "qB1", Desc: "Band", StartPos: 33536828, EndPos: 41427846, Giemsa: "gpos100", Chr: &Chr10}
	Chr10_qB2   = genome.Band{Band: "qB2", Desc: "Band", StartPos: 41427846, EndPos: 48332487, Giemsa: "gneg", Chr: &Chr10}
	Chr10_qB3   = genome.Band{Band: "qB3", Desc: "Band", StartPos: 48332487, EndPos: 56223506, Giemsa: "gpos100", Chr: &Chr10}
	Chr10_qB4   = genome.Band{Band: "qB4", Desc: "Band", StartPos: 56223506, EndPos: 64114524, Giemsa: "gneg", Chr: &Chr10}
	Chr10_qB5_1 = genome.Band{Band: "qB5.1", Desc: "Band", StartPos: 64114524, EndPos: 68060034, Giemsa: "gpos100", Chr: &Chr10}
	Chr10_qB5_2 = genome.Band{Band: "qB5.2", Desc: "Band", StartPos: 68060034, EndPos: 68553222, Giemsa: "gneg", Chr: &Chr10}
	Chr10_qB5_3 = genome.Band{Band: "qB5.3", Desc: "Band", StartPos: 68553222, EndPos: 74964675, Giemsa: "gpos100", Chr: &Chr10}
	Chr10_qC1   = genome.Band{Band: "qC1", Desc: "Band", StartPos: 74964675, EndPos: 89267146, Giemsa: "gneg", Chr: &Chr10}
	Chr10_qC2   = genome.Band{Band: "qC2", Desc: "Band", StartPos: 89267146, EndPos: 96171787, Giemsa: "gpos33", Chr: &Chr10}
	Chr10_qC3   = genome.Band{Band: "qC3", Desc: "Band", StartPos: 96171787, EndPos: 99130919, Giemsa: "gneg", Chr: &Chr10}
	Chr10_qD1   = genome.Band{Band: "qD1", Desc: "Band", StartPos: 99130919, EndPos: 111953824, Giemsa: "gpos100", Chr: &Chr10}
	Chr10_qD2   = genome.Band{Band: "qD2", Desc: "Band", StartPos: 111953824, EndPos: 124776729, Giemsa: "gneg", Chr: &Chr10}
	Chr10_qD3   = genome.Band{Band: "qD3", Desc: "Band", StartPos: 124776729, EndPos: 130694993, Giemsa: "gpos33", Chr: &Chr10}
	Chr11_qA1   = genome.Band{Band: "qA1", Desc: "Band", StartPos: 0, EndPos: 13046989, Giemsa: "gpos100", Chr: &Chr11}
	Chr11_qA2   = genome.Band{Band: "qA2", Desc: "Band", StartPos: 13046989, EndPos: 17240664, Giemsa: "gneg", Chr: &Chr11}
	Chr11_qA3_1 = genome.Band{Band: "qA3.1", Desc: "Band", StartPos: 17240664, EndPos: 21900303, Giemsa: "gpos100", Chr: &Chr11}
	Chr11_qA3_2 = genome.Band{Band: "qA3.2", Desc: "Band", StartPos: 21900303, EndPos: 25628014, Giemsa: "gneg", Chr: &Chr11}
	Chr11_qA3_3 = genome.Band{Band: "qA3.3", Desc: "Band", StartPos: 25628014, EndPos: 30287653, Giemsa: "gpos100", Chr: &Chr11}
	Chr11_qA4   = genome.Band{Band: "qA4", Desc: "Band", StartPos: 30287653, EndPos: 36345184, Giemsa: "gneg", Chr: &Chr11}
	Chr11_qA5   = genome.Band{Band: "qA5", Desc: "Band", StartPos: 36345184, EndPos: 43334643, Giemsa: "gpos100", Chr: &Chr11}
	Chr11_qB1_1 = genome.Band{Band: "qB1.1", Desc: "Band", StartPos: 43334643, EndPos: 47994282, Giemsa: "gneg", Chr: &Chr11}
	Chr11_qB1_2 = genome.Band{Band: "qB1.2", Desc: "Band", StartPos: 47994282, EndPos: 49858137, Giemsa: "gpos33", Chr: &Chr11}
	Chr11_qB1_3 = genome.Band{Band: "qB1.3", Desc: "Band", StartPos: 49858137, EndPos: 60109343, Giemsa: "gneg", Chr: &Chr11}
	Chr11_qB2   = genome.Band{Band: "qB2", Desc: "Band", StartPos: 60109343, EndPos: 62905127, Giemsa: "gpos33", Chr: &Chr11}
	Chr11_qB3   = genome.Band{Band: "qB3", Desc: "Band", StartPos: 62905127, EndPos: 70826513, Giemsa: "gneg", Chr: &Chr11}
	Chr11_qB4   = genome.Band{Band: "qB4", Desc: "Band", StartPos: 70826513, EndPos: 74088260, Giemsa: "gpos33", Chr: &Chr11}
	Chr11_qB5   = genome.Band{Band: "qB5", Desc: "Band", StartPos: 74088260, EndPos: 82009647, Giemsa: "gneg", Chr: &Chr11}
	Chr11_qC    = genome.Band{Band: "qC", Desc: "Band", StartPos: 82009647, EndPos: 90396997, Giemsa: "gpos100", Chr: &Chr11}
	Chr11_qD    = genome.Band{Band: "qD", Desc: "Band", StartPos: 90396997, EndPos: 102512059, Giemsa: "gneg", Chr: &Chr11}
	Chr11_qE1   = genome.Band{Band: "qE1", Desc: "Band", StartPos: 102512059, EndPos: 110433445, Giemsa: "gpos66", Chr: &Chr11}
	Chr11_qE2   = genome.Band{Band: "qE2", Desc: "Band", StartPos: 110433445, EndPos: 122082543, Giemsa: "gneg", Chr: &Chr11}
	Chr12_qA1_1 = genome.Band{Band: "qA1.1", Desc: "Band", StartPos: 0, EndPos: 17601321, Giemsa: "gpos100", Chr: &Chr12}
	Chr12_qA1_2 = genome.Band{Band: "qA1.2", Desc: "Band", StartPos: 17601321, EndPos: 21121586, Giemsa: "gneg", Chr: &Chr12}
	Chr12_qA1_3 = genome.Band{Band: "qA1.3", Desc: "Band", StartPos: 21121586, EndPos: 25961949, Giemsa: "gpos66", Chr: &Chr12}
	Chr12_qA2   = genome.Band{Band: "qA2", Desc: "Band", StartPos: 25961949, EndPos: 31682379, Giemsa: "gneg", Chr: &Chr12}
	Chr12_qA3   = genome.Band{Band: "qA3", Desc: "Band", StartPos: 31682379, EndPos: 39162941, Giemsa: "gpos33", Chr: &Chr12}
	Chr12_qB1   = genome.Band{Band: "qB1", Desc: "Band", StartPos: 39162941, EndPos: 44003304, Giemsa: "gneg", Chr: &Chr12}
	Chr12_qB2   = genome.Band{Band: "qB2", Desc: "Band", StartPos: 44003304, EndPos: 44883370, Giemsa: "gpos33", Chr: &Chr12}
	Chr12_qB3   = genome.Band{Band: "qB3", Desc: "Band", StartPos: 44883370, EndPos: 51923899, Giemsa: "gneg", Chr: &Chr12}
	Chr12_qC1   = genome.Band{Band: "qC1", Desc: "Band", StartPos: 51923899, EndPos: 66004957, Giemsa: "gpos100", Chr: &Chr12}
	Chr12_qC2   = genome.Band{Band: "qC2", Desc: "Band", StartPos: 66004957, EndPos: 71285353, Giemsa: "gneg", Chr: &Chr12}
	Chr12_qC3   = genome.Band{Band: "qC3", Desc: "Band", StartPos: 71285353, EndPos: 80966080, Giemsa: "gpos100", Chr: &Chr12}
	Chr12_qD1   = genome.Band{Band: "qD1", Desc: "Band", StartPos: 80966080, EndPos: 85366411, Giemsa: "gneg", Chr: &Chr12}
	Chr12_qD2   = genome.Band{Band: "qD2", Desc: "Band", StartPos: 85366411, EndPos: 88446642, Giemsa: "gpos33", Chr: &Chr12}
	Chr12_qD3   = genome.Band{Band: "qD3", Desc: "Band", StartPos: 88446642, EndPos: 95487171, Giemsa: "gneg", Chr: &Chr12}
	Chr12_qE    = genome.Band{Band: "qE", Desc: "Band", StartPos: 95487171, EndPos: 106047964, Giemsa: "gpos100", Chr: &Chr12}
	Chr12_qF1   = genome.Band{Band: "qF1", Desc: "Band", StartPos: 106047964, EndPos: 114408592, Giemsa: "gneg", Chr: &Chr12}
	Chr12_qF2   = genome.Band{Band: "qF2", Desc: "Band", StartPos: 114408592, EndPos: 120129022, Giemsa: "gpos66", Chr: &Chr12}
	Chr13_qA1   = genome.Band{Band: "qA1", Desc: "Band", StartPos: 0, EndPos: 16286533, Giemsa: "gpos100", Chr: &Chr13}
	Chr13_qA2   = genome.Band{Band: "qA2", Desc: "Band", StartPos: 16286533, EndPos: 21221846, Giemsa: "gneg", Chr: &Chr13}
	Chr13_qA3_1 = genome.Band{Band: "qA3.1", Desc: "Band", StartPos: 21221846, EndPos: 29611878, Giemsa: "gpos66", Chr: &Chr13}
	Chr13_qA3_2 = genome.Band{Band: "qA3.2", Desc: "Band", StartPos: 29611878, EndPos: 33066597, Giemsa: "gneg", Chr: &Chr13}
	Chr13_qA3_3 = genome.Band{Band: "qA3.3", Desc: "Band", StartPos: 33066597, EndPos: 41456629, Giemsa: "gpos33", Chr: &Chr13}
	Chr13_qA4   = genome.Band{Band: "qA4", Desc: "Band", StartPos: 41456629, EndPos: 44417817, Giemsa: "gneg", Chr: &Chr13}
	Chr13_qA5   = genome.Band{Band: "qA5", Desc: "Band", StartPos: 44417817, EndPos: 52807849, Giemsa: "gpos33", Chr: &Chr13}
	Chr13_qB1   = genome.Band{Band: "qB1", Desc: "Band", StartPos: 52807849, EndPos: 59223756, Giemsa: "gneg", Chr: &Chr13}
	Chr13_qB2   = genome.Band{Band: "qB2", Desc: "Band", StartPos: 59223756, EndPos: 61691413, Giemsa: "gpos33", Chr: &Chr13}
	Chr13_qB3   = genome.Band{Band: "qB3", Desc: "Band", StartPos: 61691413, EndPos: 69587914, Giemsa: "gneg", Chr: &Chr13}
	Chr13_qC1   = genome.Band{Band: "qC1", Desc: "Band", StartPos: 69587914, EndPos: 78471477, Giemsa: "gpos33", Chr: &Chr13}
	Chr13_qC2   = genome.Band{Band: "qC2", Desc: "Band", StartPos: 78471477, EndPos: 80939134, Giemsa: "gneg", Chr: &Chr13}
	Chr13_qC3   = genome.Band{Band: "qC3", Desc: "Band", StartPos: 80939134, EndPos: 94758011, Giemsa: "gpos100", Chr: &Chr13}
	Chr13_qD1   = genome.Band{Band: "qD1", Desc: "Band", StartPos: 94758011, EndPos: 106602762, Giemsa: "gneg", Chr: &Chr13}
	Chr13_qD2_1 = genome.Band{Band: "qD2.1", Desc: "Band", StartPos: 106602762, EndPos: 110551012, Giemsa: "gpos33", Chr: &Chr13}
	Chr13_qD2_2 = genome.Band{Band: "qD2.2", Desc: "Band", StartPos: 110551012, EndPos: 116473388, Giemsa: "gneg", Chr: &Chr13}
	Chr13_qD2_3 = genome.Band{Band: "qD2.3", Desc: "Band", StartPos: 116473388, EndPos: 120421639, Giemsa: "gpos33", Chr: &Chr13}
	Chr14_qA1   = genome.Band{Band: "qA1", Desc: "Band", StartPos: 0, EndPos: 14988269, Giemsa: "gpos100", Chr: &Chr14}
	Chr14_qA2   = genome.Band{Band: "qA2", Desc: "Band", StartPos: 14988269, EndPos: 19484750, Giemsa: "gneg", Chr: &Chr14}
	Chr14_qA3   = genome.Band{Band: "qA3", Desc: "Band", StartPos: 19484750, EndPos: 29976538, Giemsa: "gpos33", Chr: &Chr14}
	Chr14_qB    = genome.Band{Band: "qB", Desc: "Band", StartPos: 29976538, EndPos: 43465980, Giemsa: "gneg", Chr: &Chr14}
	Chr14_qC1   = genome.Band{Band: "qC1", Desc: "Band", StartPos: 43465980, EndPos: 51959333, Giemsa: "gpos100", Chr: &Chr14}
	Chr14_qC2   = genome.Band{Band: "qC2", Desc: "Band", StartPos: 51959333, EndPos: 54956987, Giemsa: "gneg", Chr: &Chr14}
	Chr14_qC3   = genome.Band{Band: "qC3", Desc: "Band", StartPos: 54956987, EndPos: 59953077, Giemsa: "gpos66", Chr: &Chr14}
	Chr14_qD1   = genome.Band{Band: "qD1", Desc: "Band", StartPos: 59953077, EndPos: 68946038, Giemsa: "gneg", Chr: &Chr14}
	Chr14_qD2   = genome.Band{Band: "qD2", Desc: "Band", StartPos: 68946038, EndPos: 72942910, Giemsa: "gpos33", Chr: &Chr14}
	Chr14_qD3   = genome.Band{Band: "qD3", Desc: "Band", StartPos: 72942910, EndPos: 84933525, Giemsa: "gneg", Chr: &Chr14}
	Chr14_qE1   = genome.Band{Band: "qE1", Desc: "Band", StartPos: 84933525, EndPos: 88930397, Giemsa: "gpos66", Chr: &Chr14}
	Chr14_qE2_1 = genome.Band{Band: "qE2.1", Desc: "Band", StartPos: 88930397, EndPos: 98922577, Giemsa: "gpos100", Chr: &Chr14}
	Chr14_qE2_2 = genome.Band{Band: "qE2.2", Desc: "Band", StartPos: 98922577, EndPos: 99921795, Giemsa: "gneg", Chr: &Chr14}
	Chr14_qE2_3 = genome.Band{Band: "qE2.3", Desc: "Band", StartPos: 99921795, EndPos: 107415929, Giemsa: "gpos100", Chr: &Chr14}
	Chr14_qE3   = genome.Band{Band: "qE3", Desc: "Band", StartPos: 107415929, EndPos: 110913192, Giemsa: "gneg", Chr: &Chr14}
	Chr14_qE4   = genome.Band{Band: "qE4", Desc: "Band", StartPos: 110913192, EndPos: 120905372, Giemsa: "gpos100", Chr: &Chr14}
	Chr14_qE5   = genome.Band{Band: "qE5", Desc: "Band", StartPos: 120905372, EndPos: 124902244, Giemsa: "gneg", Chr: &Chr14}
	Chr15_qA1   = genome.Band{Band: "qA1", Desc: "Band", StartPos: 0, EndPos: 16500320, Giemsa: "gpos100", Chr: &Chr15}
	Chr15_qA2   = genome.Band{Band: "qA2", Desc: "Band", StartPos: 16500320, EndPos: 24292137, Giemsa: "gneg", Chr: &Chr15}
	Chr15_qB1   = genome.Band{Band: "qB1", Desc: "Band", StartPos: 24292137, EndPos: 29792244, Giemsa: "gpos33", Chr: &Chr15}
	Chr15_qB2   = genome.Band{Band: "qB2", Desc: "Band", StartPos: 29792244, EndPos: 32083955, Giemsa: "gneg", Chr: &Chr15}
	Chr15_qB3_1 = genome.Band{Band: "qB3.1", Desc: "Band", StartPos: 32083955, EndPos: 43084169, Giemsa: "gpos100", Chr: &Chr15}
	Chr15_qB3_2 = genome.Band{Band: "qB3.2", Desc: "Band", StartPos: 43084169, EndPos: 44917538, Giemsa: "gneg", Chr: &Chr15}
	Chr15_qB3_3 = genome.Band{Band: "qB3.3", Desc: "Band", StartPos: 44917538, EndPos: 49959302, Giemsa: "gpos66", Chr: &Chr15}
	Chr15_qC    = genome.Band{Band: "qC", Desc: "Band", StartPos: 49959302, EndPos: 53626040, Giemsa: "gneg", Chr: &Chr15}
	Chr15_qD1   = genome.Band{Band: "qD1", Desc: "Band", StartPos: 53626040, EndPos: 66459622, Giemsa: "gpos100", Chr: &Chr15}
	Chr15_qD2   = genome.Band{Band: "qD2", Desc: "Band", StartPos: 66459622, EndPos: 68751333, Giemsa: "gneg", Chr: &Chr15}
	Chr15_qD3   = genome.Band{Band: "qD3", Desc: "Band", StartPos: 68751333, EndPos: 77459835, Giemsa: "gpos66", Chr: &Chr15}
	Chr15_qE1   = genome.Band{Band: "qE1", Desc: "Band", StartPos: 77459835, EndPos: 83876627, Giemsa: "gneg", Chr: &Chr15}
	Chr15_qE2   = genome.Band{Band: "qE2", Desc: "Band", StartPos: 83876627, EndPos: 87085022, Giemsa: "gpos33", Chr: &Chr15}
	Chr15_qE3   = genome.Band{Band: "qE3", Desc: "Band", StartPos: 87085022, EndPos: 95793524, Giemsa: "gneg", Chr: &Chr15}
	Chr15_qF1   = genome.Band{Band: "qF1", Desc: "Band", StartPos: 95793524, EndPos: 101293631, Giemsa: "gpos66", Chr: &Chr15}
	Chr15_qF2   = genome.Band{Band: "qF2", Desc: "Band", StartPos: 101293631, EndPos: 102210316, Giemsa: "gneg", Chr: &Chr15}
	Chr15_qF3   = genome.Band{Band: "qF3", Desc: "Band", StartPos: 102210316, EndPos: 104043685, Giemsa: "gpos33", Chr: &Chr15}
	Chr16_qA1   = genome.Band{Band: "qA1", Desc: "Band", StartPos: 0, EndPos: 15432649, Giemsa: "gpos100", Chr: &Chr16}
	Chr16_qA2   = genome.Band{Band: "qA2", Desc: "Band", StartPos: 15432649, EndPos: 16367961, Giemsa: "gneg", Chr: &Chr16}
	Chr16_qA3   = genome.Band{Band: "qA3", Desc: "Band", StartPos: 16367961, EndPos: 20576865, Giemsa: "gpos33", Chr: &Chr16}
	Chr16_qB1   = genome.Band{Band: "qB1", Desc: "Band", StartPos: 20576865, EndPos: 26188738, Giemsa: "gneg", Chr: &Chr16}
	Chr16_qB2   = genome.Band{Band: "qB2", Desc: "Band", StartPos: 26188738, EndPos: 32268266, Giemsa: "gpos33", Chr: &Chr16}
	Chr16_qB3   = genome.Band{Band: "qB3", Desc: "Band", StartPos: 32268266, EndPos: 38347795, Giemsa: "gneg", Chr: &Chr16}
	Chr16_qB4   = genome.Band{Band: "qB4", Desc: "Band", StartPos: 38347795, EndPos: 44894979, Giemsa: "gpos33", Chr: &Chr16}
	Chr16_qB5   = genome.Band{Band: "qB5", Desc: "Band", StartPos: 44894979, EndPos: 53780444, Giemsa: "gneg", Chr: &Chr16}
	Chr16_qC1_1 = genome.Band{Band: "qC1.1", Desc: "Band", StartPos: 53780444, EndPos: 57989348, Giemsa: "gpos66", Chr: &Chr16}
	Chr16_qC1_2 = genome.Band{Band: "qC1.2", Desc: "Band", StartPos: 57989348, EndPos: 58924660, Giemsa: "gneg", Chr: &Chr16}
	Chr16_qC1_3 = genome.Band{Band: "qC1.3", Desc: "Band", StartPos: 58924660, EndPos: 66874813, Giemsa: "gpos66", Chr: &Chr16}
	Chr16_qC2   = genome.Band{Band: "qC2", Desc: "Band", StartPos: 66874813, EndPos: 70616061, Giemsa: "gneg", Chr: &Chr16}
	Chr16_qC3_1 = genome.Band{Band: "qC3.1", Desc: "Band", StartPos: 70616061, EndPos: 79033870, Giemsa: "gpos100", Chr: &Chr16}
	Chr16_qC3_2 = genome.Band{Band: "qC3.2", Desc: "Band", StartPos: 79033870, EndPos: 79501526, Giemsa: "gneg", Chr: &Chr16}
	Chr16_qC3_3 = genome.Band{Band: "qC3.3", Desc: "Band", StartPos: 79501526, EndPos: 91660583, Giemsa: "gpos100", Chr: &Chr16}
	Chr16_qC4   = genome.Band{Band: "qC4", Desc: "Band", StartPos: 91660583, EndPos: 98207768, Giemsa: "gneg", Chr: &Chr16}
	Chr17_qA1   = genome.Band{Band: "qA1", Desc: "Band", StartPos: 0, EndPos: 13943085, Giemsa: "gpos100", Chr: &Chr17}
	Chr17_qA2   = genome.Band{Band: "qA2", Desc: "Band", StartPos: 13943085, EndPos: 16121692, Giemsa: "gneg", Chr: &Chr17}
	Chr17_qA3_1 = genome.Band{Band: "qA3.1", Desc: "Band", StartPos: 16121692, EndPos: 17428857, Giemsa: "gpos33", Chr: &Chr17}
	Chr17_qA3_2 = genome.Band{Band: "qA3.2", Desc: "Band", StartPos: 17428857, EndPos: 21786071, Giemsa: "gneg", Chr: &Chr17}
	Chr17_qA3_3 = genome.Band{Band: "qA3.3", Desc: "Band", StartPos: 21786071, EndPos: 31371942, Giemsa: "gpos66", Chr: &Chr17}
	Chr17_qB1   = genome.Band{Band: "qB1", Desc: "Band", StartPos: 31371942, EndPos: 40086371, Giemsa: "gneg", Chr: &Chr17}
	Chr17_qB2   = genome.Band{Band: "qB2", Desc: "Band", StartPos: 40086371, EndPos: 41393535, Giemsa: "gpos33", Chr: &Chr17}
	Chr17_qB3   = genome.Band{Band: "qB3", Desc: "Band", StartPos: 41393535, EndPos: 45750749, Giemsa: "gneg", Chr: &Chr17}
	Chr17_qC    = genome.Band{Band: "qC", Desc: "Band", StartPos: 45750749, EndPos: 55772342, Giemsa: "gpos66", Chr: &Chr17}
	Chr17_qD    = genome.Band{Band: "qD", Desc: "Band", StartPos: 55772342, EndPos: 60129556, Giemsa: "gneg", Chr: &Chr17}
	Chr17_qE1_1 = genome.Band{Band: "qE1.1", Desc: "Band", StartPos: 60129556, EndPos: 67972542, Giemsa: "gpos100", Chr: &Chr17}
	Chr17_qE1_2 = genome.Band{Band: "qE1.2", Desc: "Band", StartPos: 67972542, EndPos: 68843985, Giemsa: "gneg", Chr: &Chr17}
	Chr17_qE1_3 = genome.Band{Band: "qE1.3", Desc: "Band", StartPos: 68843985, EndPos: 73201199, Giemsa: "gpos100", Chr: &Chr17}
	Chr17_qE2   = genome.Band{Band: "qE2", Desc: "Band", StartPos: 73201199, EndPos: 78429856, Giemsa: "gneg", Chr: &Chr17}
	Chr17_qE3   = genome.Band{Band: "qE3", Desc: "Band", StartPos: 78429856, EndPos: 82787071, Giemsa: "gpos33", Chr: &Chr17}
	Chr17_qE4   = genome.Band{Band: "qE4", Desc: "Band", StartPos: 82787071, EndPos: 88887171, Giemsa: "gneg", Chr: &Chr17}
	Chr17_qE5   = genome.Band{Band: "qE5", Desc: "Band", StartPos: 88887171, EndPos: 94987271, Giemsa: "gpos33", Chr: &Chr17}
	Chr18_qA1   = genome.Band{Band: "qA1", Desc: "Band", StartPos: 0, EndPos: 19406146, Giemsa: "gpos100", Chr: &Chr18}
	Chr18_qA2   = genome.Band{Band: "qA2", Desc: "Band", StartPos: 19406146, EndPos: 29531091, Giemsa: "gneg", Chr: &Chr18}
	Chr18_qB1   = genome.Band{Band: "qB1", Desc: "Band", StartPos: 29531091, EndPos: 35437310, Giemsa: "gpos66", Chr: &Chr18}
	Chr18_qB2   = genome.Band{Band: "qB2", Desc: "Band", StartPos: 35437310, EndPos: 37124801, Giemsa: "gneg", Chr: &Chr18}
	Chr18_qB3   = genome.Band{Band: "qB3", Desc: "Band", StartPos: 37124801, EndPos: 45562255, Giemsa: "gpos100", Chr: &Chr18}
	Chr18_qC    = genome.Band{Band: "qC", Desc: "Band", StartPos: 45562255, EndPos: 49780983, Giemsa: "gneg", Chr: &Chr18}
	Chr18_qD1   = genome.Band{Band: "qD1", Desc: "Band", StartPos: 49780983, EndPos: 53999710, Giemsa: "gpos100", Chr: &Chr18}
	Chr18_qD2   = genome.Band{Band: "qD2", Desc: "Band", StartPos: 53999710, EndPos: 54421583, Giemsa: "gneg", Chr: &Chr18}
	Chr18_qD3   = genome.Band{Band: "qD3", Desc: "Band", StartPos: 54421583, EndPos: 60749674, Giemsa: "gpos100", Chr: &Chr18}
	Chr18_qE1   = genome.Band{Band: "qE1", Desc: "Band", StartPos: 60749674, EndPos: 67921511, Giemsa: "gneg", Chr: &Chr18}
	Chr18_qE2   = genome.Band{Band: "qE2", Desc: "Band", StartPos: 67921511, EndPos: 75093347, Giemsa: "gpos33", Chr: &Chr18}
	Chr18_qE3   = genome.Band{Band: "qE3", Desc: "Band", StartPos: 75093347, EndPos: 83530802, Giemsa: "gneg", Chr: &Chr18}
	Chr18_qE4   = genome.Band{Band: "qE4", Desc: "Band", StartPos: 83530802, EndPos: 90702639, Giemsa: "gpos33", Chr: &Chr18}
	Chr19_qA    = genome.Band{Band: "qA", Desc: "Band", StartPos: 0, EndPos: 16680094, Giemsa: "gpos100", Chr: &Chr19}
	Chr19_qB    = genome.Band{Band: "qB", Desc: "Band", StartPos: 16680094, EndPos: 25630388, Giemsa: "gneg", Chr: &Chr19}
	Chr19_qC1   = genome.Band{Band: "qC1", Desc: "Band", StartPos: 25630388, EndPos: 34987514, Giemsa: "gpos66", Chr: &Chr19}
	Chr19_qC2   = genome.Band{Band: "qC2", Desc: "Band", StartPos: 34987514, EndPos: 38242166, Giemsa: "gneg", Chr: &Chr19}
	Chr19_qC3   = genome.Band{Band: "qC3", Desc: "Band", StartPos: 38242166, EndPos: 47599292, Giemsa: "gpos66", Chr: &Chr19}
	Chr19_qD1   = genome.Band{Band: "qD1", Desc: "Band", StartPos: 47599292, EndPos: 51667608, Giemsa: "gneg", Chr: &Chr19}
	Chr19_qD2   = genome.Band{Band: "qD2", Desc: "Band", StartPos: 51667608, EndPos: 58990576, Giemsa: "gpos33", Chr: &Chr19}
	Chr19_qD3   = genome.Band{Band: "qD3", Desc: "Band", StartPos: 58990576, EndPos: 61431566, Giemsa: "gneg", Chr: &Chr19}
	ChrX_qA1_1  = genome.Band{Band: "qA1.1", Desc: "Band", StartPos: 0, EndPos: 15772338, Giemsa: "gpos100", Chr: &ChrX}
	ChrX_qA1_2  = genome.Band{Band: "qA1.2", Desc: "Band", StartPos: 15772338, EndPos: 18236766, Giemsa: "gneg", Chr: &ChrX}
	ChrX_qA1_3  = genome.Band{Band: "qA1.3", Desc: "Band", StartPos: 18236766, EndPos: 21194080, Giemsa: "gpos33", Chr: &ChrX}
	ChrX_qA2    = genome.Band{Band: "qA2", Desc: "Band", StartPos: 21194080, EndPos: 28094478, Giemsa: "gneg", Chr: &ChrX}
	ChrX_qA3_1  = genome.Band{Band: "qA3.1", Desc: "Band", StartPos: 28094478, EndPos: 33516219, Giemsa: "gpos66", Chr: &ChrX}
	ChrX_qA3_2  = genome.Band{Band: "qA3.2", Desc: "Band", StartPos: 33516219, EndPos: 34501991, Giemsa: "gneg", Chr: &ChrX}
	ChrX_qA3_3  = genome.Band{Band: "qA3.3", Desc: "Band", StartPos: 34501991, EndPos: 39923732, Giemsa: "gpos66", Chr: &ChrX}
	ChrX_qA4    = genome.Band{Band: "qA4", Desc: "Band", StartPos: 39923732, EndPos: 47809902, Giemsa: "gneg", Chr: &ChrX}
	ChrX_qA5    = genome.Band{Band: "qA5", Desc: "Band", StartPos: 47809902, EndPos: 56188957, Giemsa: "gpos66", Chr: &ChrX}
	ChrX_qA6    = genome.Band{Band: "qA6", Desc: "Band", StartPos: 56188957, EndPos: 63089355, Giemsa: "gneg", Chr: &ChrX}
	ChrX_qA7_1  = genome.Band{Band: "qA7.1", Desc: "Band", StartPos: 63089355, EndPos: 69496867, Giemsa: "gpos66", Chr: &ChrX}
	ChrX_qA7_2  = genome.Band{Band: "qA7.2", Desc: "Band", StartPos: 69496867, EndPos: 70975524, Giemsa: "gneg", Chr: &ChrX}
	ChrX_qA7_3  = genome.Band{Band: "qA7.3", Desc: "Band", StartPos: 70975524, EndPos: 77383037, Giemsa: "gpos66", Chr: &ChrX}
	ChrX_qB     = genome.Band{Band: "qB", Desc: "Band", StartPos: 77383037, EndPos: 82311893, Giemsa: "gneg", Chr: &ChrX}
	ChrX_qC1    = genome.Band{Band: "qC1", Desc: "Band", StartPos: 82311893, EndPos: 91183833, Giemsa: "gpos100", Chr: &ChrX}
	ChrX_qC2    = genome.Band{Band: "qC2", Desc: "Band", StartPos: 91183833, EndPos: 92169604, Giemsa: "gneg", Chr: &ChrX}
	ChrX_qC3    = genome.Band{Band: "qC3", Desc: "Band", StartPos: 92169604, EndPos: 101041545, Giemsa: "gpos100", Chr: &ChrX}
	ChrX_qD     = genome.Band{Band: "qD", Desc: "Band", StartPos: 101041545, EndPos: 109913486, Giemsa: "gneg", Chr: &ChrX}
	ChrX_qE1    = genome.Band{Band: "qE1", Desc: "Band", StartPos: 109913486, EndPos: 120264083, Giemsa: "gpos100", Chr: &ChrX}
	ChrX_qE2    = genome.Band{Band: "qE2", Desc: "Band", StartPos: 120264083, EndPos: 121249854, Giemsa: "gneg", Chr: &ChrX}
	ChrX_qE3    = genome.Band{Band: "qE3", Desc: "Band", StartPos: 121249854, EndPos: 135050651, Giemsa: "gpos100", Chr: &ChrX}
	ChrX_qF1    = genome.Band{Band: "qF1", Desc: "Band", StartPos: 135050651, EndPos: 141458163, Giemsa: "gneg", Chr: &ChrX}
	ChrX_qF2    = genome.Band{Band: "qF2", Desc: "Band", StartPos: 141458163, EndPos: 148851447, Giemsa: "gpos33", Chr: &ChrX}
	ChrX_qF3    = genome.Band{Band: "qF3", Desc: "Band", StartPos: 148851447, EndPos: 156244731, Giemsa: "gneg", Chr: &ChrX}
	ChrX_qF4    = genome.Band{Band: "qF4", Desc: "Band", StartPos: 156244731, EndPos: 163638015, Giemsa: "gpos33", Chr: &ChrX}
	ChrX_qF5    = genome.Band{Band: "qF5", Desc: "Band", StartPos: 163638015, EndPos: 171031299, Giemsa: "gneg", Chr: &ChrX}
	ChrY_qA1    = genome.Band{Band: "qA1", Desc: "Band", StartPos: 0, EndPos: 20642557, Giemsa: "gpos100", Chr: &ChrY}
	ChrY_qA2    = genome.Band{Band: "qA2", Desc: "Band", StartPos: 20642557, EndPos: 32684048, Giemsa: "gpos66", Chr: &ChrY}
	ChrY_qB     = genome.Band{Band: "qB", Desc: "Band", StartPos: 32684048, EndPos: 45298944, Giemsa: "gpos33", Chr: &ChrY}
	ChrY_qC1    = genome.Band{Band: "qC1", Desc: "Band", StartPos: 45298944, EndPos: 54473414, Giemsa: "gpos100", Chr: &ChrY}
	ChrY_qC2    = genome.Band{Band: "qC2", Desc: "Band", StartPos: 54473414, EndPos: 61927671, Giemsa: "gpos33", Chr: &ChrY}
	ChrY_qC3    = genome.Band{Band: "qC3", Desc: "Band", StartPos: 61927671, EndPos: 72248949, Giemsa: "gpos100", Chr: &ChrY}
	ChrY_qD     = genome.Band{Band: "qD", Desc: "Band", StartPos: 72248949, EndPos: 83143632, Giemsa: "gpos33", Chr: &ChrY}
	ChrY_qE     = genome.Band{Band: "qE", Desc: "Band", StartPos: 83143632, EndPos: 91744698, Giemsa: "gpos66", Chr: &ChrY}
)

var Bands = []*genome.Band{
	&Chr1_qA1,
	&Chr1_qA2,
	&Chr1_qA3,
	&Chr1_qA4,
	&Chr1_qA5,
	&Chr1_qB,
	&Chr1_qC1_1,
	&Chr1_qC1_2,
	&Chr1_qC1_3,
	&Chr1_qC2,
	&Chr1_qC3,
	&Chr1_qC4,
	&Chr1_qC5,
	&Chr1_qD,
	&Chr1_qE1_1,
	&Chr1_qE1_2,
	&Chr1_qE2_1,
	&Chr1_qE2_2,
	&Chr1_qE2_3,
	&Chr1_qE3,
	&Chr1_qE4,
	&Chr1_qF,
	&Chr1_qG1,
	&Chr1_qG2,
	&Chr1_qG3,
	&Chr1_qH1,
	&Chr1_qH2_1,
	&Chr1_qH2_2,
	&Chr1_qH2_3,
	&Chr1_qH3,
	&Chr1_qH4,
	&Chr1_qH5,
	&Chr1_qH6,
	&Chr2_qA1,
	&Chr2_qA2,
	&Chr2_qA3,
	&Chr2_qB,
	&Chr2_qC1_1,
	&Chr2_qC1_2,
	&Chr2_qC1_3,
	&Chr2_qC2,
	&Chr2_qC3,
	&Chr2_qD,
	&Chr2_qE1,
	&Chr2_qE2,
	&Chr2_qE3,
	&Chr2_qE4,
	&Chr2_qE5,
	&Chr2_qF1,
	&Chr2_qF2,
	&Chr2_qF3,
	&Chr2_qG1,
	&Chr2_qG2,
	&Chr2_qG3,
	&Chr2_qH1,
	&Chr2_qH2,
	&Chr2_qH3,
	&Chr2_qH4,
	&Chr3_qA1,
	&Chr3_qA2,
	&Chr3_qA3,
	&Chr3_qB,
	&Chr3_qC,
	&Chr3_qD,
	&Chr3_qE1,
	&Chr3_qE2,
	&Chr3_qE3,
	&Chr3_qF1,
	&Chr3_qF2_1,
	&Chr3_qF2_2,
	&Chr3_qF2_3,
	&Chr3_qF3,
	&Chr3_qG1,
	&Chr3_qG2,
	&Chr3_qG3,
	&Chr3_qH1,
	&Chr3_qH2,
	&Chr3_qH3,
	&Chr3_qH4,
	&Chr4_qA1,
	&Chr4_qA2,
	&Chr4_qA3,
	&Chr4_qA4,
	&Chr4_qA5,
	&Chr4_qB1,
	&Chr4_qB2,
	&Chr4_qB3,
	&Chr4_qC1,
	&Chr4_qC2,
	&Chr4_qC3,
	&Chr4_qC4,
	&Chr4_qC5,
	&Chr4_qC6,
	&Chr4_qC7,
	&Chr4_qD1,
	&Chr4_qD2_1,
	&Chr4_qD2_2,
	&Chr4_qD2_3,
	&Chr4_qD3,
	&Chr4_qE1,
	&Chr4_qE2,
	&Chr5_qA1,
	&Chr5_qA2,
	&Chr5_qA3,
	&Chr5_qB1,
	&Chr5_qB2,
	&Chr5_qB3,
	&Chr5_qC1,
	&Chr5_qC2,
	&Chr5_qC3_1,
	&Chr5_qC3_2,
	&Chr5_qC3_3,
	&Chr5_qD,
	&Chr5_qE1,
	&Chr5_qE2,
	&Chr5_qE3,
	&Chr5_qE4,
	&Chr5_qE5,
	&Chr5_qF,
	&Chr5_qG1_1,
	&Chr5_qG1_2,
	&Chr5_qG1_3,
	&Chr5_qG2,
	&Chr5_qG3,
	&Chr6_qA1,
	&Chr6_qA2,
	&Chr6_qA3_1,
	&Chr6_qA3_2,
	&Chr6_qA3_3,
	&Chr6_qB1,
	&Chr6_qB2_1,
	&Chr6_qB2_2,
	&Chr6_qB2_3,
	&Chr6_qB3,
	&Chr6_qC1,
	&Chr6_qC2,
	&Chr6_qC3,
	&Chr6_qD1,
	&Chr6_qD2,
	&Chr6_qD3,
	&Chr6_qE1,
	&Chr6_qE2,
	&Chr6_qE3,
	&Chr6_qF1,
	&Chr6_qF2,
	&Chr6_qF3,
	&Chr6_qG1,
	&Chr6_qG2,
	&Chr6_qG3,
	&Chr7_qA1,
	&Chr7_qA2,
	&Chr7_qA3,
	&Chr7_qB1,
	&Chr7_qB2,
	&Chr7_qB3,
	&Chr7_qB4,
	&Chr7_qB5,
	&Chr7_qC,
	&Chr7_qD1,
	&Chr7_qD2,
	&Chr7_qD3,
	&Chr7_qE1,
	&Chr7_qE2,
	&Chr7_qE3,
	&Chr7_qF1,
	&Chr7_qF2,
	&Chr7_qF3,
	&Chr7_qF4,
	&Chr7_qF5,
	&Chr8_qA1_1,
	&Chr8_qA1_2,
	&Chr8_qA1_3,
	&Chr8_qA2,
	&Chr8_qA3,
	&Chr8_qA4,
	&Chr8_qB1_1,
	&Chr8_qB1_2,
	&Chr8_qB1_3,
	&Chr8_qB2,
	&Chr8_qB3_1,
	&Chr8_qB3_2,
	&Chr8_qB3_3,
	&Chr8_qC1,
	&Chr8_qC2,
	&Chr8_qC3,
	&Chr8_qC4,
	&Chr8_qC5,
	&Chr8_qD1,
	&Chr8_qD2,
	&Chr8_qD3,
	&Chr8_qE1,
	&Chr8_qE2,
	&Chr9_qA1,
	&Chr9_qA2,
	&Chr9_qA3,
	&Chr9_qA4,
	&Chr9_qA5_1,
	&Chr9_qA5_2,
	&Chr9_qA5_3,
	&Chr9_qB,
	&Chr9_qC,
	&Chr9_qD,
	&Chr9_qE1,
	&Chr9_qE2,
	&Chr9_qE3_1,
	&Chr9_qE3_2,
	&Chr9_qE3_3,
	&Chr9_qE4,
	&Chr9_qF1,
	&Chr9_qF2,
	&Chr9_qF3,
	&Chr9_qF4,
	&Chr10_qA1,
	&Chr10_qA2,
	&Chr10_qA3,
	&Chr10_qA4,
	&Chr10_qB1,
	&Chr10_qB2,
	&Chr10_qB3,
	&Chr10_qB4,
	&Chr10_qB5_1,
	&Chr10_qB5_2,
	&Chr10_qB5_3,
	&Chr10_qC1,
	&Chr10_qC2,
	&Chr10_qC3,
	&Chr10_qD1,
	&Chr10_qD2,
	&Chr10_qD3,
	&Chr11_qA1,
	&Chr11_qA2,
	&Chr11_qA3_1,
	&Chr11_qA3_2,
	&Chr11_qA3_3,
	&Chr11_qA4,
	&Chr11_qA5,
	&Chr11_qB1_1,
	&Chr11_qB1_2,
	&Chr11_qB1_3,
	&Chr11_qB2,
	&Chr11_qB3,
	&Chr11_qB4,
	&Chr11_qB5,
	&Chr11_qC,
	&Chr11_qD,
	&Chr11_qE1,
	&Chr11_qE2,
	&Chr12_qA1_1,
	&Chr12_qA1_2,
	&Chr12_qA1_3,
	&Chr12_qA2,
	&Chr12_qA3,
	&Chr12_qB1,
	&Chr12_qB2,
	&Chr12_qB3,
	&Chr12_qC1,
	&Chr12_qC2,
	&Chr12_qC3,
	&Chr12_qD1,
	&Chr12_qD2,
	&Chr12_qD3,
	&Chr12_qE,
	&Chr12_qF1,
	&Chr12_qF2,
	&Chr13_qA1,
	&Chr13_qA2,
	&Chr13_qA3_1,
	&Chr13_qA3_2,
	&Chr13_qA3_3,
	&Chr13_qA4,
	&Chr13_qA5,
	&Chr13_qB1,
	&Chr13_qB2,
	&Chr13_qB3,
	&Chr13_qC1,
	&Chr13_qC2,
	&Chr13_qC3,
	&Chr13_qD1,
	&Chr13_qD2_1,
	&Chr13_qD2_2,
	&Chr13_qD2_3,
	&Chr14_qA1,
	&Chr14_qA2,
	&Chr14_qA3,
	&Chr14_qB,
	&Chr14_qC1,
	&Chr14_qC2,
	&Chr14_qC3,
	&Chr14_qD1,
	&Chr14_qD2,
	&Chr14_qD3,
	&Chr14_qE1,
	&Chr14_qE2_1,
	&Chr14_qE2_2,
	&Chr14_qE2_3,
	&Chr14_qE3,
	&Chr14_qE4,
	&Chr14_qE5,
	&Chr15_qA1,
	&Chr15_qA2,
	&Chr15_qB1,
	&Chr15_qB2,
	&Chr15_qB3_1,
	&Chr15_qB3_2,
	&Chr15_qB3_3,
	&Chr15_qC,
	&Chr15_qD1,
	&Chr15_qD2,
	&Chr15_qD3,
	&Chr15_qE1,
	&Chr15_qE2,
	&Chr15_qE3,
	&Chr15_qF1,
	&Chr15_qF2,
	&Chr15_qF3,
	&Chr16_qA1,
	&Chr16_qA2,
	&Chr16_qA3,
	&Chr16_qB1,
	&Chr16_qB2,
	&Chr16_qB3,
	&Chr16_qB4,
	&Chr16_qB5,
	&Chr16_qC1_1,
	&Chr16_qC1_2,
	&Chr16_qC1_3,
	&Chr16_qC2,
	&Chr16_qC3_1,
	&Chr16_qC3_2,
	&Chr16_qC3_3,
	&Chr16_qC4,
	&Chr17_qA1,
	&Chr17_qA2,
	&Chr17_qA3_1,
	&Chr17_qA3_2,
	&Chr17_qA3_3,
	&Chr17_qB1,
	&Chr17_qB2,
	&Chr17_qB3,
	&Chr17_qC,
	&Chr17_qD,
	&Chr17_qE1_1,
	&Chr17_qE1_2,
	&Chr17_qE1_3,
	&Chr17_qE2,
	&Chr17_qE3,
	&Chr17_qE4,
	&Chr17_qE5,
	&Chr18_qA1,
	&Chr18_qA2,
	&Chr18_qB1,
	&Chr18_qB2,
	&Chr18_qB3,
	&Chr18_qC,
	&Chr18_qD1,
	&Chr18_qD2,
	&Chr18_qD3,
	&Chr18_qE1,
	&Chr18_qE2,
	&Chr18_qE3,
	&Chr18_qE4,
	&Chr19_qA,
	&Chr19_qB,
	&Chr19_qC1,
	&Chr19_qC2,
	&Chr19_qC3,
	&Chr19_qD1,
	&Chr19_qD2,
	&Chr19_qD3,
	&ChrX_qA1_1,
	&ChrX_qA1_2,
	&ChrX_qA1_3,
	&ChrX_qA2,
	&ChrX_qA3_1,
	&ChrX_qA3_2,
	&ChrX_qA3_3,
	&ChrX_qA4,
	&ChrX_qA5,
	&ChrX_qA6,
	&ChrX_qA7_1,
	&ChrX_qA7_2,
	&ChrX_qA7_3,
	&ChrX_qB,
	&ChrX_qC1,
	&ChrX_qC2,
	&ChrX_qC3,
	&ChrX_qD,
	&ChrX_qE1,
	&ChrX_qE2,
	&ChrX_qE3,
	&ChrX_qF1,
	&ChrX_qF2,
	&ChrX_qF3,
	&ChrX_qF4,
	&ChrX_qF5,
	&ChrY_qA1,
	&ChrY_qA2,
	&ChrY_qB,
	&ChrY_qC1,
	&ChrY_qC2,
	&ChrY_qC3,
	&ChrY_qD,
	&ChrY_qE,
}

//line parse.karyotype:82
func init() {
	for _, b := range Bands {
		b.Chr.(*genome.Chromosome).Features = append(b.Chr.(*genome.Chromosome).Features, b)
	}
	for _, c := range Chromosomes {
		bc := make([]feat.Feature, len(c.Features))
		copy(bc, c.Features)
		c.Features = bc
	}
}
